use_frameworks!

target 'MAGPdfGenerator_Example' do
  pod 'MAGPdfGenerator', :path => '../'
  pod 'ORStackView', '~> 3.0'
  pod 'Masonry', '~> 1.0'
  pod 'ZXingObjC', '~> 3.1'

  target 'MAGPdfGenerator_Tests' do
    inherit! :search_paths

    
  end
end
